version: "3.3"
services:

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: luizalabs
      POSTGRES_USER: luiza
      POSTGRES_PASSWORD: labs
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  luizalabs-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    image: luizalabs-challenge:latest
    depends_on:
      - database
    ports:
      - "3000:3000"
    env_file:
      - ./.env
