version: "3.9"
services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: luiza
      POSTGRES_PASSWORD: luizalabs

  luizalabs-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    image: luizalabs-challenge:latest
    depends_on:
      - database
    ports:
      - "3000:3000"
    env_file:
      - ./.env
